#apiVersion: kustomize.config.k8s.io/v1beta1
apiVersion: kustomize.toolkit.fluxcd.io/v1  
  #kind: Kustomization
  #resources:
  #- gotk-components.yaml
  #- gotk-sync.yaml
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ../k8s-manifest   # point to the folder with your secrets and deployments
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
