apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:oMdXFdH24lg85KWD+qgtJn0qV7frVG88puwiLs0Vu5xYyp9ymfEFuvqiD4hjx9+agGNsqRsRDOzM4zhcLodMiwrrt+gQ9cmrz7CuAVgK3Wl3ViiSEdpTuiwCCUqXYoAH7KuUBARC8X5cJMAAWpD4RAcwtApy0M/8qeZKpbzLe0JPoK1NMsQ3ZbAG1TQ8Vg/jzbf+eXYRUvfT+wnzv8HfZEh6A1GPOZBLwizHvehUupY1kmb5fej84jZiZEnwHhCa52gWGb8MWoahyze7IwBfnNAxoD1WVsz4AdxeTYTILlscUDzvCfTLm3kySJ5MzYgK9OHkWY8PihOrROFWX9nAYcntmezKR9k5SpsfkOHY2rDMie7p44v39Ur9N+3f/lWmLR6TFI0MqjPSf2sRdCyPdB3RzL5pxHINRll0IX2uxfdIXSaioT9AsisLYtbzhc16usGIVg==,iv:772w8M/yIV239XvurLyGOrMwaOQOovngi4tNZy20ITY=,tag:YnaxCdA+IHPCrAbhYlCtTw==,type:str]
kind: Secret
metadata:
    name: acr-secret
    namespace: bmo
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-03-04T01:27:45Z"
    mac: ENC[AES256_GCM,data:xOHMpsKt0aF177pOs2lOxGLFDna1IqN9bxFIWvofwGuA9Dd3oC+Q0ciocRnI4Ry2TS5eY3hyvBdF4xzlFCtqV0LqGU8mLbnKrqSmNnJeUbNJJlyuZhCURs+Ka6Jtqdlfwm94A/EO4AS2sEKdCGcUDuO9vK0FtfU9iiTFIrfw7Co=,iv:78LKdZQAYpTZ7P0Su5AyDuXPUGohvT+83+9Mhq3KIdY=,tag:vC4wOZ1jqU680CO3iwtSjw==,type:str]
    pgp:
        - created_at: "2026-03-04T01:27:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA8WegH98Uk14AQv/WHrwDM0HETsOdwa4sBISUOeWKz1abKnOQiPfI6EGugjB
            k1txOz2NdsM4rWqNt69Nfd2CvX9pMF7og0BYyg3Wgg+FCIVnqPRG5mR6qYlCupUE
            oZ+fLttiaiW1uoGOqvoArrNjrM5xFk9zP/bXfVax8ACqGgUQSDf0+bPC+ECnYn8S
            sQRHio/O1w/K6TpI08uZLp4HVtIk9hrVDRH5e1UkRuuP9zUmQDulL6dsSaYuKi+d
            +UG70ERyBuDtMQmI+6WuPyDtBGNmlnB17kB0antP1taAXR6DzBI/6umstrOfRDob
            qdvnLxHm+29OX5iiEkeSXqlfHs7Gzl9icaYi4rqWoS+XGc4B6d1GOR5aLSkKyROu
            oHHYJUtL2+EPaIbsX9mnNHCqML/1O9Ip4cf+N83JhGAFfE5b04mTtVIuyzEIAVnt
            8GAAS0kZhl5Wjsv4QwRDxdJ1gj2GR/YdVoDAAsf6b4QFqUcz/ss/cwRQSKgxLawS
            wkx8A+KS+V0vEzm6DEoO1GgBCQIQjax6sh5F1s036a6svjQyRPe69YAl2T2AwvwA
            TdzrzuBqr4Y7JEcXCtm1V0PhxJLHrTHIDBkjAXr0ZVaCV2gNhgRGTUiFUy0D7Hap
            /cx8qCsW/2+03lefM+vBnBrerM0uSyOHXw==
            =S+jx
            -----END PGP MESSAGE-----
          fp: B8F53A7F8BF5657FC03334AF4C96528872C54290
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
