apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJibW9kZW1vYWNyLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiI2MWQyNDhjMS00MmVhLTQ1YTEtYjI2Ny0yYzc0Yjc3YTYxYmMiLCJwYXNzd29yZCI6IkxpRjhRfk5HaldqY2Y4QnVNRy5wbnNRaUQwVkc5d0lxMWxvWjlhNXgiLCJhdXRoIjoiTmpGa01qUTRZekV0TkRKbFlTMDBOV0V4TFdJeU5qY3RNbU0zTkdJM04yRTJNV0pqT2t4cFJqaFJmazVIYWxkcVkyWTRRblZOUnk1d2JuTlJhVVF3VmtjNWQwbHhNV3h2V2psaE5YZz0ifX19
kind: Secret
metadata:
  name: acr-secret
  namespace: bmo
type: kubernetes.io/dockerconfigjson
